# Tutorial 11: Test inference + shapley values REST API Endpoint 

In this notebook, we will demonstrate how to perform inference using an ML model deployed as a REST API endpoint. REST API will also filter columns that are not needed for the prediction. Output of the inference will include  reason codes (shapley values) in addition to the prediction.

## Steps
- Import requests and pandas libraries. Requests is an elegant and simple HTTP library for Python, built for human beings. More about requests [here](https://docs.python-requests.org/en/latest/)
- Create a pandas dataframe for the data on which we want to perform inference
- Copy the REST API endpoint from _Models_ tab
- Create a json from the pandas dataframe
- Add additional columns to test column filter
- Create a header for a post request
- Perform a post request on the REST API endpoint

In [8]:
import requests
import pandas as pd
import numpy as np
import joblib

## Get test data

In [3]:
input_df = pd.read_csv("credit_card_test_new_columns.csv")
y_test = input_df["Target"]
X_test = input_df.drop(["Target"],axis=1)

## Add extra columns to reproduce real case

In [4]:
X_test["V100"] = X_test["V22"]
X_test["V200"] = X_test["V23"]*0.9

## Test REST API Endpoint

In [19]:
%%time 

url = "https://k1yltn5.rmlpoc.net/invocations"
input_data = X_test.head(10)
data_json = input_data.to_json(orient="split",index=False)
headers = {"Content-Type":"application/json; format=pandas-split"}
response = requests.post(url,data=data_json,headers=headers)

CPU times: user 11.3 ms, sys: 3.57 ms, total: 14.9 ms
Wall time: 39.5 ms

In [20]:
response.json()

[0, 0, 1, 0, 1, 0, 0, 0, 0, 0]

In [15]:
input_data

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,cc_exp,lat1,long1,lat2,long2,lat3,long3,ip_address,V100,V200
0,160760.0,-0.674466,1.408105,-1.110622,-1.328366,1.388996,-1.308439,1.885879,-0.614233,0.311652,...,01/23,81.627882,-100.863399,88.659301,179.866492,15.609163,-8.823885,195.127.246.134,0.810034,-0.201895
1,19847.0,-2.829816,-2.765149,2.537793,-1.074580,2.842559,-2.153536,-1.795519,-0.250020,3.073504,...,10/27,-53.558042,-46.830667,24.180878,16.312487,-69.282235,-80.631857,221.9.126.196,0.109305,-0.731945
2,88326.0,-3.576495,2.318422,1.306985,3.263665,1.127818,2.865246,1.444125,-0.718922,1.874046,...,08/30,-33.831702,-142.765298,-73.259027,-44.841458,-70.108155,-154.769389,214.77.126.181,0.016867,-0.118852
3,141734.0,2.060386,-0.015382,-1.082544,0.386019,-0.024331,-1.074935,0.207792,-0.338140,0.455091,...,10/30,-74.512890,-61.924700,-57.572207,-30.457993,24.175755,-83.299702,141.124.211.66,-0.639426,0.298636
4,38741.0,1.209965,1.384303,-1.343531,1.763636,0.662351,-2.113384,0.854039,-0.475963,-0.629658,...,12/22,49.083962,165.716597,-20.392087,-39.059461,-85.666065,169.884538,197.201.179.126,-0.328294,-0.139168
5,151934.0,-0.345588,1.070328,-0.652790,-0.492207,0.749482,-0.949391,0.752520,0.079095,0.061269,...,01/27,87.659946,136.167049,-54.402779,103.832347,74.434146,29.429568,112.180.5.227,-0.843460,0.168722
6,159122.0,-0.864273,0.361412,-0.346667,-1.938227,-1.065839,-1.056202,-0.093590,0.095647,-2.782531,...,10/31,-54.346516,160.390803,82.109498,-140.632704,-39.643957,72.387986,212.216.124.139,-0.162751,0.107555
7,41656.0,-1.679000,0.004724,2.093100,-0.209994,1.112123,-1.254060,0.193846,-0.010860,-0.568361,...,09/23,-67.018063,-68.049700,45.497728,86.709826,-27.672311,177.710189,136.185.169.115,-0.540966,-0.050977
8,52202.0,-0.806445,0.865983,1.105898,1.383957,-0.018110,0.140882,0.124651,0.603672,-0.853074,...,06/26,-38.591268,-42.851621,-37.379534,-8.876108,-63.715060,-127.410471,147.221.195.98,0.494319,-0.002675
9,52081.0,1.169646,-0.823924,0.467031,-0.840968,-0.850688,0.062139,-0.705097,0.094004,-1.020702,...,10/30,50.610906,-32.146348,-40.268943,-136.331650,22.521534,-80.302968,43.97.156.133,0.030735,-0.004528